# 查询课程信息

POST {{content_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

  {
  "auditStatus": "202004",
  "courseName": "",
  "publishStatus": ""
}

### 查询根节点的信息
GET {{content_host}}/content/course-category/tree-nodes


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json
{
  "mt": "",
  "st": "",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "",
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "",
  "wechat": "",
  "phone": "",
  "validDays": 365
}



